#!/usr/bin/env php
<?php

/**
 * @file
 * This file serves as the application entrypoint.
 */

declare(strict_types = 1);

require_once $_composer_autoload_path ?? __DIR__ . '/vendor/autoload.php';

$connection_factory ??= new \LibraryMarket\msadiag\SMTP\ConnectionFactory();

$commands = [
  new \LibraryMarket\msadiag\Command\ProbeEncryptionCommand(connection_factory: $connection_factory),
  new \LibraryMarket\msadiag\Command\ProbeExtensionsCommand(connection_factory: $connection_factory),
  new \LibraryMarket\msadiag\Command\ValidateCommand(connection_factory: $connection_factory),
];

$application = new \Symfony\Component\Console\Application('msadiag');

foreach ($commands as $command) {
  $application->add($command);
}

$application->run();
