name: 'PHPStan'
on: [push]
jobs:
  testing:
    name: 'PHPStan'
    runs-on: ubuntu-24.04
    steps:
      - name: 'Add PHP PPA'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -qq install software-properties-common
          sudo apt-add-repository -y ppa:ondrej/php
          sudo apt-get update
      - name: 'Install system dependencies'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq install curl php-cli php-zip
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === 'ed0feb545ba87161262f2d45a633e34f591ebb3381f2e0063c345ebea4d228dd0043083717770234ec00c5a9f9593792') { echo 'Installer verified'.PHP_EOL; } else { echo 'Installer corrupt'.PHP_EOL; unlink('composer-setup.php'); exit(1); }"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          sudo mv composer.phar /usr/local/bin/composer
      - name: 'Print enabled PHP extensions'
        run: 'php -m'
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      - name: 'Install Composer dependencies'
        run: 'composer install --no-interaction --no-progress'
      - name: 'Run PHPStan tests'
        run: './vendor/bin/phpstan analyze --no-progress --level=max src'
